### ISSUE TITLE
safari - Invalid match arg: /(\r?\n|\r)+/

### ISSUE THREAD

**Issue by tiensonqin** [intception/om-dropzone#1]
Invalid match arg: /(\r?\n|\r)+/
replacestring.cljs:33
markdown__delegateutils.cljs:26
markdownutils.cljs:26
(anonymous function)tower.cljs:45
compile_dict_pathtower.cljs:51
apply__3core.cljs:2833
applycore.cljs:2853
G__11870__delegatecore.cljs:3209
G__11870core.cljs:3209
(anonymous function)core.cljs:3541
svalcore.cljs:2396
cljs$core$ISeqable$_seq$arity$1core.cljs:2388
_seqcore.cljs:308
seqcore.cljs:627
cljs$core$INext$_next$arity$1core.js:6889
_nextcore.cljs:255
nextcore.cljs:672
bounded_countcore.cljs:2695
apply__3core.cljs:2827
applycore.cljs:2853
compile_dict_innertower.cljs:59
compile_dicttower.cljs:78

**Comment by tiensonqin** [comment]
I can confirm the issue is net.unit8/tower-cljs,
switch to tower works fine!

**Comment by kernelp4nic** [comment]
Awesome, thanks!

**Comment by kernelp4nic** [comment]
Wait, tower is a clj lib, what do you mean? Do you know if its working with the latest version of tower-cljs?
